[Chore] add ssh keep-alive option

diff --git a/.github/workflows/blog-actions.yml b/.github/workflows/blog-actions.yml
--- a/.github/workflows/blog-actions.yml
+++ b/.github/workflows/blog-actions.yml
@@ -30,5 +30,5 @@ jobs:
         run: |
           echo "${{ secrets.NCP_SSH_KEY }}" > _temp_key
           chmod 600 _temp_key
-          ssh -o StrictHostKeyChecking=no -p 20002 -i _temp_key ${{ secrets.NCP_SSH_USER }}@${{ secrets.NCP_SSH_HOST }} 'docker pull ${{ secrets.DOCKER_USERNAME }}/blog-actions:latest && docker-compose -f /home/docker/docker-compose.yml up -d'
+          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o ConnectTimeout=30 -p 20002 -i _temp_key ${{ secrets.NCP_SSH_USER }}@${{ secrets.NCP_SSH_HOST }} 'docker pull ${{ secrets.DOCKER_USERNAME }}/blog-actions:latest && docker-compose -f /home/docker/docker-compose.yml up -d' || echo "SSH command failed, retrying..." && sleep 10 && ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o ConnectTimeout=30 -p 20002 -i _temp_key ${{ secrets.NCP_SSH_USER }}@${{ secrets.NCP_SSH_HOST }} 'docker pull ${{ secrets.DOCKER_USERNAME }}/blog-actions:latest && docker-compose -f /home/docker/docker-compose.yml up -d'
           rm _temp_key
